FROM joezuntz/desc-pipe-base:1.0
MAINTAINER joezuntz@googlemail.com

# Install the file implementing this module.
# Should really do this from github tagged version.
COPY tomography.py /opt/desc/

# Always end with this.
USER vagrant
